namespace Mhora.Definitions
{
	public enum AakritiYoga
	{
		None                = 0,
		AakritiArdhachandra = 1,
		AakritiChakra       = 2,
		AakritiChhatra      = 3,
		AakritiDanda        = 4,
		AakritiDhanush      = 5,
		AakritiGada         = 6,
		AakritiHalaMoksha   = 7,
		AakritiHalaKama     = 8,
		AakritiHalaArtha    = 9,
		AakritiKoota        = 10,
		AakritiNauka        = 11,
		AakritiPakshi       = 12,
		AakritiSamudra      = 13,
		AakritiShakata      = 14,
		AakritiShakti       = 15,
		AakritiShara        = 16,
		AakritiShringataka  = 17,
		AakritiVaapi        = 18,
		AakritiVajra        = 19,
		AakritiYava         = 20,
		AakritiYoopa        = 21,
	}

	public enum ChandraYoga
	{
		None                = 0,
		ChandraAdhi         = 1,
		ChandraAnapha       = 2,
		ChandraDurudhara    = 3,
		ChandraKalpadruma1  = 4,
		ChandraKalpadruma2  = 5,
		ChandraKalpadruma3  = 6,
		ChandraKalpadruma4  = 7,
		ChandraKalpadruma5  = 8,
		ChandraKalpadruma6  = 9,
		ChandraKalpadruma7  = 10,
		ChandraKalpadruma8  = 11,
		ChandraKalpadruma9  = 12,
		ChandraKalpadruma10 = 13,
		ChandraKalpadruma11 = 14,
		ChandraKalpadruma12 = 15,
		ChandraKalpadruma13 = 16,
		ChandraKalpadruma14 = 17,
		ChandraKalpadruma15 = 18,
		ChandraKalpadruma16 = 19,
		ChandraKalpadruma17 = 20,
		ChandraKalpadruma18 = 21,
		ChandraKalpadruma19 = 22,
		ChandraKalpadruma20 = 23,
		ChandraSunapha		= 24,
	}

	public enum DhanaYoga
	{
		None              = 0,
		DhanaSurya        = 1,
		DhanaGuru5th      = 2,
		DhanaLagna        = 3,
		DhanaChandra      = 4,
		Dhana2ndHouseLord = 5,
		DanaShukraLagna   = 6,
		DhanaGuru9th      = 7,
		DhanaBuddh5th     = 8,
		DhanaBuddhLagna   = 9,
		DhanaShukra5th    = 10,
		DhanaGuruLagna    = 11,
		DhanaShaniLagna   = 12,
		DhanaShani5th     = 13,
		DhanaMangal5th    = 14,
		DhanaChandra5th   = 15,
		DhanaSurya5th     = 16,
		Dhana9thLord      = 17,
		Dhana5thLord      = 18,
		DhanaMangalLagna  = 19,
		DhanaBhava        = 20,
		DhanaNight        = 21,
		DhanaDay          = 22,
	}

	public enum GenericYoga
	{
		None               = 0,
		GajaKesariChandra  = 1,
		GrahaYoga          = 2,
		HariHaraBramha7th  = 3,
		HariHaraBramha2nd  = 4,
		HariHaraBramha1st  = 5,
		KalsarpaYoga       = 6,
		RaviUbhaychariYoga = 7,
		RaviVeshiYoga      = 8,
		RaviVoshiYoga      = 9,
		SankhyaYoga        = 10,
		AashrayaMusala     = 11,
		AashrayaNala       = 12,
		AashrayaRajju      = 13,
		AmalaKirti         = 14,
		AmaraYogaBenefics  = 15,
		AmaraYogaMalefics  = 16,
		Bheri              = 17,
		Chaamara1          = 18,
		Chaamara2          = 19,
		ChatussagaraKendra = 20,
		ChatussagaraChara  = 21,
		DalaMala           = 22,
		DalaSarpa          = 23,
		DalaMaala          = 24,
		Dhwaja             = 25,
		Hamsa              = 26,
		HathaHantaa        = 27,
		Indra              = 28,
		Kaahala1           = 29,
		Kaahala2           = 30,
		Karika             = 31,
		PaapaKartari       = 32,
		ShubhaKartari      = 33,
		Khadga             = 34,
		Lagnadhi           = 35,
		Lakshmi            = 36,
		MahaBhagyaNight    = 37,
		MahaBhagyaDay      = 38,
		MahaPataka         = 39,
		ParvataKendra      = 40,
		ParvataLagna       = 41,
		Saraswati          = 42,
		Shakata            = 43,
		Shankha            = 44,
		Shrinatha          = 45,
		Simhasana          = 46,
		AlpaUttamadi       = 47,
		MadhyaUttamadi     = 48,
		UttamaUttamadi     = 49,
		Vasumna            = 50,
	}

	public enum MahaParivartanaYoga
	{
		None              = 0,
		MahaParivartana1  = 1,
		MahaParivartana2  = 2,
		MahaParivartana4  = 3,
		MahaParivartana5  = 4,
		MahaParivartana7  = 5,
		MahaParivartana9  = 6,
		MahaParivartana10 = 7
	}

	public enum MahapurushaYoga
	{
		None                   = 0,
		MahapurushaBhadraBuddh = 1,
		MahapurushaHamsa       = 2,
		MahapurushaMalavya     = 3,
		MahapurushaRuchaka     = 4,
		MahapurushaSasha       = 5
	}

	public enum MalikaYoga
	{
		None          = 0,
		LabhaMalika   = 1,
		DhanuMalika   = 2,
		BhagyaMalika  = 3,
		LagnaMalika   = 4,
		KalatraMalika = 5,
		KarmaMalika   = 6,
		PutraMalika   = 7,
		RandhraMalika = 8,
		SatruMalika   = 9,
		SukhaMalika   = 10,
		VrayaMalika   = 11
	}

	public enum RajaYoga
	{
		None               = 0,
		Raja1              = 1,
		Raja2              = 2,
		Raja3              = 3,
		Raja4              = 4,
		Raja5              = 5,
		Raja6              = 6,
		Raja7              = 7,
		Raja8              = 8,
		Raja9              = 9,
		Raja10             = 10,
		Raja11             = 11,
		Raja12             = 12,
		Raja13             = 13,
		Raja14             = 14,
		Raja15             = 15,
		Raja16             = 16,
		Raja17             = 17,
		Raja18             = 18,
		Raja19             = 19,
		Raja20             = 20,
		Raja21             = 21,
		Raja22             = 22,
		Raja23             = 23,
		ViparitaHarshaRaja = 24,
		ViparitaSaralaRaja = 25,
		ViparitaVimalaRaja = 26,
	}
}
